### ISSUE TITLE
关于DIY中的提交

### ISSUE THREAD

**Issue by Shangke7788** [NJUST-FishTeam/NJUST_OnlineJudge_M6_BugReport#1]
DIY Contest一般会圈其它OJ的题目，如果提交这些代理的题目的话会发现不是用自己绑定的账号提交的，能否改成也是自己绑定的账号提交？

**Comment by comzyh** [comment]
注意到这个问题了,
不过还没想好是不是应该用绑定账号提交.
我个人觉得应该允许用绑定账号提交.
