### ISSUE TITLE
水题榜当用 Zju 和 Hdu 排序时出现人名与内容不符合的bug。

### ISSUE THREAD

**Issue by yunfanLu** [NJUST-FishTeam/NJUST_OnlineJudge_M6_BugReport#15]
当从 “/base/UserInfo.txt” 里读出所有人名后，左边的人名是根据 sum 进行排序的。每个人人根据sum有一个index。当基于 Hdu 或者 Zoj 排序时，人们的排序会改变。所以这里的 index 会改变。进而导致了人与内容不符合的bug。

``` HTML
<a onclick="getgragh('2')" class="static-a ">黄莘(Alwa)</a>
```

``` JavaScript
function getgragh(index){...} //这里传进来的是index，当排序后index和人名并非对应。所以较为简单的修改方法就是把 index 改成 username 然后在找到正确的 index 。
```

现在感觉有两种解决方法：
1，直接把 index 变成 username ，再通过 username 找到正确的 index。
2，在排序的时候，右边这一栏也跟着变化。

**Comment by ShengRang** [comment]
fixed
