### ISSUE TITLE
OJ怎么不评测了？。。

### ISSUE THREAD

**Issue by netcan** [NJUST-FishTeam/NJUST_OnlineJudge_M6_BugReport#16]
OJ怎么不评测了？。。

**Comment by comzyh** [comment]
谢谢提醒，我去看看。

**Comment by comzyh** [comment]
修好啦~

**Comment by netcan** [comment]
..头像怎么换啊。。

**Comment by comzyh** [comment]
@netcan https://cn.gravatar.com/

**Comment by lalawuu** [comment]
IGN评测

**Comment by comzyh** [comment]
啥？ 发自网易邮箱大师 在2016年02月06日 12:24 ，bisunday写道： IGN评测 — Reply to this email directly or view it on GitHub.
