### ISSUE TITLE
Zoj与Hdu无法提交

### ISSUE THREAD

**Issue by Tribleave** [NJUST-FishTeam/NJUST_OnlineJudge_M6_BugReport#19]
2016/8/18

**Comment by comzyh** [comment]
我们看到 ZOJ 是没有办法访问的，如果你有方法能够访问 ZOJ，请告诉我们，我们会想办法解决

HDU 目前遇到了技术故障，我们正在准备一些临时方法补救，如果你有更好的方法，也请告诉我们

感谢反馈

**Comment by comzyh** [comment]
HDU 代理已修复
