### ISSUE TITLE
Submit Failed

### ISSUE THREAD

**Issue by NENightElves** [NJUST-FishTeam/NJUST_OnlineJudge_M6_BugReport#20]
![screenshot_2016-11-02-11-38-19-347_com android browser](https://cloud.githubusercontent.com/assets/9031334/19915985/ff31404c-a0f0-11e6-833a-1f269d146b74.png)
![screenshot_2016-11-02-11-40-52-321_com android browser](https://cloud.githubusercontent.com/assets/9031334/19916020/44643462-a0f1-11e6-9da4-b8119dac8db8.png)

**Comment by comzyh** [comment]
这几题看起来是PAT上已经关闭的题目集里的题目，现在无法提交我们也没办法。

**Comment by ShengRang** [comment]
PAT题库的1000-1086这些题是浙大已经关闭的题目集里面的题目， 已经无法提交。 

后续会关闭这些题目， 或者标记不可用

**Comment by NENightElves** [comment]
知道了，谢谢~
