### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by NENightElves** [NJUST-FishTeam/NJUST_OnlineJudge_M6_BugReport#21]
相同的代码在myeclipse编译通过，在oj平台java编译错误

**Comment by NENightElves** [comment]
![qq 20161119114427](https://cloud.githubusercontent.com/assets/9031334/20452837/427d8292-ae4e-11e6-8bc1-8085e487e015.png)
![qq 20161119114717](https://cloud.githubusercontent.com/assets/9031334/20452838/46aeccb8-ae4e-11e6-98f1-f88fafba4616.png)

**Comment by ShengRang** [comment]
你好， 这是由于你的代码中包含中文字符（注释）。
我们推荐提交的代码中不要包含中文字符， 中文标点等字符。

**Comment by NENightElves** [comment]
已收到解决方案，谢谢~将关闭问题。
