### ISSUE TITLE
关于抓题的HTML语言解析

### ISSUE THREAD

**Issue by Shangke7788** [NJUST-FishTeam/NJUST_OnlineJudge_M6_BugReport#3]
![qq20140603213825](https://cloud.githubusercontent.com/assets/7513653/3160743/6617cf2c-eb24-11e3-8e45-586a0adf25eb.jpg)
其中的&quot;是转义符，能否显示成原符号，或许会更好一点。：）

**Comment by comzyh** [comment]
才看见.
ZOJ 3193 回去确认下是哪里的问题.
有可能是抓的时候就有问题,也有可能是输出的时候转义了.

**Comment by maemual** [comment]
题目已编辑
