### ISSUE TITLE
在题目页面登陆快捷键冲突及焦点丢失问题

### ISSUE THREAD

**Issue by maemual** [NJUST-FishTeam/NJUST_OnlineJudge_M6_BugReport#4]
1、在我禁用浏览器插件vimium时，在登陆administrator输入到s时，焦点丢失

2、部分快捷键与vimium插件冲突

建议取消

**Comment by comzyh** [comment]
已修复,
登陆时快捷键禁用
如果永久禁用,进入/LocalSettings/设置即可
27日上线
